In [1]:
import pandas as pd

In [2]:
fleet_peformance = pd.read_excel("/content/20260213_Fleet_Performance.xlsx")

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

3407 instances (rows) , 45 features (columns)

In [4]:
fleet_peformance.shape

(3407, 45)

In [3]:
fleet_peformance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3407 entries, 0 to 3406
Data columns (total 45 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Row Status                                           3407 non-null   object
 1   Period                                               3407 non-null   int64
 2   Incident Number                                      3407 non-null   object
 3   Incident Date                                        3407 non-null   datetime64[ns]
 4   Headcode                                             1647 non-null   object
 5   Train                                                3084 non-null   object
 6   Incident Location                                    3339 non-null   object
 7   TARA Primary Delay Minutes                           2737 non-null   float64
 8   TARA Canx                                            2736 non-null   float64
 9   Primary Mins Sum                                     3373 non-null   float64
 10  Total Mins                                           3407 non-null   float64
 11  Sum Canx                                             3387 non-null   float64
 12  Equipment Bugle                                      3378 non-null   object
 13  Vehicle No.                                          1234 non-null   object
 14  Unit No.                                             3385 non-null   object
 15  Coupled Unit No.                                     372 non-null    object
 16  5-9 Car                                              3331 non-null   float64
 17  Train Type                                           3384 non-null   object
 18  Train Accepted                                       2699 non-null   datetime64[ns]
 19  LNER Investigation Notes                             3373 non-null   object
 20  Hitachi Investigation Notes / SAP info / Root Cause  3070 non-null   object
 21  LNER Status Notes                                    2083 non-null   object
 22  Bugle Mgr                                            3099 non-null   object
 23  Trust Mgr                                            3387 non-null   object
 24  Inc Cause                                            3387 non-null   object
 25  Root Cause                                           2677 non-null   object
 26  Bugle Dispute Status                                 3387 non-null   object
 27  Bugle Status                                         3387 non-null   object
 28  LNER Fleet Status                                    3407 non-null   object
 29  Report Requested From/Delay Attributed To:           207 non-null    object
 30  Master Incident Number                               3407 non-null   object
 31  Date Report Requested/Referred or Delay Closed Out   450 non-null    object
 32  Hitachi Status                                       2800 non-null   object
 33  Tech                                                 3053 non-null   object
 34  TIN                                                  3407 non-null   int64
 35  KPI Code                                             3386 non-null   object
 36  Cause Code                                           2910 non-null   object
 37  System                                               2909 non-null   object
 38  Subsystem                                            2909 non-null   object
 39  Failure                                              2895 non-null   object
 40  Engineering Comments                                 2349 non-null   object
 41  EFC (if Required) In Progress?                       3 non-null      object
 42  PHRD?                                                0 non-null      float64
 43  PHRD Number                                          1 non-null      float64
 44  PIP/MOD Recommended?                                 0 non-null      float64
dtypes: datetime64[ns](2), float64(9), int64(2), object(32)
memory usage: 1.2+ MB

In [5]:
fleet_peformance.head()

,Row Status,Period,Incident Number,Incident Date,Headcode,Train,Incident Location,TARA Primary Delay Minutes,TARA Canx,Primary Mins Sum,...,KPI Code,Cause Code,System,Subsystem,Failure,Engineering Comments,EFC (if Required) In Progress?,PHRD?,PHRD Number,PIP/MOD Recommended?
0,New,2612,192749,2026-02-12,1E15,09:52 ABERDEEN to KINGS X,EDB MNK,17.0,0.0,17.0,...,701D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,New,2612,192000,2026-02-12,5S08,06:34 FERMEPARK to KINGS X,FRMPKRS,5.0,0.0,5.0,...,701A,1DB,Operational,NR,Regulation,Unit late off depot.,NaN,NaN,NaN,NaN
2,New,2612,191778,2026-02-12,5A02,NaN,XNL,NaN,NaN,59.0,...,701D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,New,2612,191716,2026-02-12,3Y03,04:35 DONCARIEP to YORK\nRunning as 04:57 DONC...,DON,10.0,0.0,10.0,...,701D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Root Cause, Bugle Dispute Status",2612,190994,2026-02-11,1D26,18:03 KINGS X to SKIPTON,DON,11.0,0.0,11.0,...,701D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Warning: Total number of columns (45) exceeds max_columns (20) limiting to first (20) columns.

In [6]:
fleet_peformance.isnull().sum()

Row Status                                                0
Period                                                    0
Incident Number                                           0
Incident Date                                             0
Headcode                                               1760
Train                                                   323
Incident Location                                        68
TARA Primary Delay Minutes                              670
TARA Canx                                               671
Primary Mins Sum                                         34
Total Mins                                                0
Sum Canx                                                 20
Equipment Bugle                                          29
Vehicle No.                                            2173
Unit No.                                                 22
Coupled Unit No.                                       3035
5-9 Car                                                  76
Train Type                                               23
Train Accepted                                          708
LNER Investigation Notes                                 34
Hitachi Investigation Notes / SAP info / Root Cause     337
LNER Status Notes                                      1324
Bugle Mgr                                               308
Trust Mgr                                                20
Inc Cause                                                20
Root Cause                                              730
Bugle Dispute Status                                     20
Bugle Status                                             20
LNER Fleet Status                                         0
Report Requested From/Delay Attributed To:             3200
Master Incident Number                                    0
Date Report Requested/Referred or Delay Closed Out     2957
Hitachi Status                                          607
Tech                                                    354
TIN                                                       0
KPI Code                                                 21
Cause Code                                              497
System                                                  498
Subsystem                                               498
Failure                                                 512
Engineering Comments                                   1058
EFC (if Required) In Progress?                         3404
PHRD?                                                  3407
PHRD Number                                            3406
PIP/MOD Recommended?                                   3407
dtype: int64

These variables have 0–2% missing, which is excellent: Incident Date, Total Mins, Period, Incident Number,  Incident Location, Primary Mins Sum ,Train Type ,Sum Canx

These are reliable and suitable for analysis.

In [7]:
fleet_peformance.isna().sum()/len(fleet_peformance)*100

Row Status                                               0.000000
Period                                                   0.000000
Incident Number                                          0.000000
Incident Date                                            0.000000
Headcode                                                51.658350
Train                                                    9.480481
Incident Location                                        1.995891
TARA Primary Delay Minutes                              19.665395
TARA Canx                                               19.694746
Primary Mins Sum                                         0.997945
Total Mins                                               0.000000
Sum Canx                                                 0.587027
Equipment Bugle                                          0.851189
Vehicle No.                                             63.780452
Unit No.                                                 0.645729
Coupled Unit No.                                        89.081303
5-9 Car                                                  2.230701
Train Type                                               0.675081
Train Accepted                                          20.780746
LNER Investigation Notes                                 0.997945
Hitachi Investigation Notes / SAP info / Root Cause      9.891400
LNER Status Notes                                       38.861168
Bugle Mgr                                                9.040211
Trust Mgr                                                0.587027
Inc Cause                                                0.587027
Root Cause                                              21.426475
Bugle Dispute Status                                     0.587027
Bugle Status                                             0.587027
LNER Fleet Status                                        0.000000
Report Requested From/Delay Attributed To:              93.924274
Master Incident Number                                   0.000000
Date Report Requested/Referred or Delay Closed Out      86.791899
Hitachi Status                                          17.816261
Tech                                                    10.390373
TIN                                                      0.000000
KPI Code                                                 0.616378
Cause Code                                              14.587614
System                                                  14.616965
Subsystem                                               14.616965
Failure                                                 15.027884
Engineering Comments                                    31.053713
EFC (if Required) In Progress?                          99.911946
PHRD?                                                  100.000000
PHRD Number                                             99.970649
PIP/MOD Recommended?                                   100.000000
dtype: float64

In [ ]:
# columns potentially  to use

#time variables - Incdient date, period

#Delay impact (Important) - Total Mins, Primary Mins Sum, TARA Primary Delay Minutes

#Cancellation indicator - Sum Canx, TARA Canx

#Location context - Incident Location

#Train information - Train Type, Unit No.

#cause/engineering info - Inc Cause, Root Cause, Cause Code, System, Subsystem, Failure

In [ ]:
#we need smth to predict or detect risk:

#eg. Predict high delay incidents: High Delay = Total Mins > 30, Predict Cancellation risk, Predict availability pressure perios - based on: total delay mins, incident frequency, cause types.

In [8]:
Fleet_delay = pd.read_excel("/content/Fleet Dealy Data from P2301 to P2611.xlsx")

3925 instances (rows), 55 features (columns)

In [9]:
Fleet_delay.shape

(3925, 55)

In [11]:
Fleet_delay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 55 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Inc.#                 3925 non-null   int64
 1   Date                  3925 non-null   datetime64[ns]
 2   Status                3925 non-null   object
 3   Bugle Mgr             3925 non-null   object
 4   Bugle Mgr Title       3925 non-null   object
 5   Trust Mgr             3925 non-null   object
 6   NR Mgr                3925 non-null   object
 7   Cause                 3925 non-null   object
 8   Root Cause            3792 non-null   object
 9   Root Cause Descrip.   3925 non-null   object
 10  Incid. Location       3918 non-null   object
 11  Comment               3925 non-null   object
 12  Equip.                3924 non-null   object
 13  Tot. Mins             3925 non-null   float64
 14  Inc. Mins Delay Mins  3925 non-null   float64
 15  Delay Mins            3925 non-null   float64
 16  Capes                 3925 non-null   float64
 17  Pines                 3925 non-null   float64
 18  Calvs                 3925 non-null   float64
 19  FTS                   3925 non-null   int64
 20  Trains Affect         3925 non-null   int64
 21  EQ Mins               3925 non-null   float64
 22  Mgrs Note             3925 non-null   object
 23  KPI                   3925 non-null   object
 24  Bugle Status          3925 non-null   object
 25  RSP Week              3925 non-null   object
 26  Inc. Pd               3925 non-null   object
 27  DfT Full              3925 non-null   float64
 28  DfT Part              3925 non-null   float64
 29  CaSL                  3925 non-null   float64
 30  PPM Fail              3925 non-null   float64
 31  Incid. #              3925 non-null   int64
 32  Div.s                 3925 non-null   object
 33  Company               3925 non-null   object
 34  Full Canx             3925 non-null   float64
 35  Part Canx             3925 non-null   float64
 36  Total Canx            3925 non-null   float64
 37  Sig. Lates            3925 non-null   float64
 38  Total Mins            3925 non-null   float64
 39  W/E                   3925 non-null   datetime64[ns]
 40  Rep. Period           3925 non-null   int64
 41  KPI Cat.              3925 non-null   int64
 42  CaSL's                3925 non-null   float64
 43  PPM Fails             3925 non-null   float64
 44  Sect1                 3925 non-null   object
 45  Region.               3925 non-null   object
 46  Sect2                 3925 non-null   object
 47  Day 8                 3925 non-null   datetime64[ns]
 48  NR KPI                3925 non-null   object
 49  TOC1                  3925 non-null   object
 50  TOC2                  3925 non-null   object
 51  Region                3925 non-null   object
 52  Funct.                3925 non-null   object
 53  Unnamed: 53           0 non-null      float64
 54  1246.5                0 non-null      float64
dtypes: datetime64[ns](3), float64(20), int64(6), object(26)
memory usage: 1.6+ MB

In [12]:
Fleet_delay.head()

,Inc.#,Date,Status,Bugle Mgr,Bugle Mgr Title,Trust Mgr,NR Mgr,Cause,Root Cause,Root Cause Descrip.,...,Region.,Sect2,Day 8,NR KPI,TOC1,TOC2,Region,Funct.,Unnamed: 53,1246.5
0,480134220401,2022-04-01,A,MHB2,HITACHI - CLASS 801,MHB2,OQIE,MN,NaN,No Root Cause entered,...,Azuma,Hitachi - Class 801,2022-04-08,Fleet,HB,LNER,Azuma,Azuma,NaN,NaN
1,485541220403,2022-04-03,A,MHBK,YARD - CRAIGENTINNY,MHBK,OQL9,MU,NaN,No Root Cause entered,...,Depot,Craigentinny,2022-04-10,Depot,HB,LNER,Depot,Azuma,NaN,NaN
2,485877220403,2022-04-03,A,MHB1,HITACHI - CLASS 800,MHB1,OQI8,MY,MY05,Class 800/801 Couplers,...,Azuma,Hitachi - Class 800,2022-04-10,Fleet,HB,LNER,Azuma,Azuma,NaN,NaN
3,487346220404,2022-04-04,A,MHB1,HITACHI - CLASS 800,MHB1,OQI8,M7,M703,PASSENGER DOOR,...,Azuma,Hitachi - Class 800,2022-04-11,Fleet,HB,LNER,Azuma,Azuma,NaN,NaN
4,488234220404,2022-04-04,A,MHBA,FLEET - CLASS 91 LOCOMOTIVE,MHBA,OQIJ,MB,NaN,No Root Cause entered,...,IC225,Cl 91 Loco,2022-04-11,Fleet,HB,LNER,IC225,IC225,NaN,NaN

Warning: Total number of columns (55) exceeds max_columns (20) limiting to first (20) columns.

In [13]:
Fleet_delay.isnull().sum()

Inc.#                      0
Date                       0
Status                     0
Bugle Mgr                  0
Bugle Mgr Title            0
Trust Mgr                  0
NR Mgr                     0
Cause                      0
Root Cause               133
Root Cause Descrip.        0
Incid. Location            7
Comment                    0
Equip.                     1
Tot. Mins                  0
Inc. Mins Delay Mins       0
Delay Mins                 0
Capes                      0
Pines                      0
Calvs                      0
FTS                        0
Trains Affect              0
EQ Mins                    0
Mgrs Note                  0
KPI                        0
Bugle Status               0
RSP Week                   0
Inc. Pd                    0
DfT Full                   0
DfT Part                   0
CaSL                       0
PPM Fail                   0
Incid. #                   0
Div.s                      0
Company                    0
Full Canx                  0
Part Canx                  0
Total Canx                 0
Sig. Lates                 0
Total Mins                 0
W/E                        0
Rep. Period                0
KPI Cat.                   0
CaSL's                     0
PPM Fails                  0
Sect1                      0
Region.                    0
Sect2                      0
Day 8                      0
NR KPI                     0
TOC1                       0
TOC2                       0
Region                     0
Funct.                     0
Unnamed: 53             3925
1246.5                  3925
dtype: int64

In [14]:
Fleet_delay.isna().sum()/len(Fleet_delay)*100

Inc.#                     0.000000
Date                      0.000000
Status                    0.000000
Bugle Mgr                 0.000000
Bugle Mgr Title           0.000000
Trust Mgr                 0.000000
NR Mgr                    0.000000
Cause                     0.000000
Root Cause                3.388535
Root Cause Descrip.       0.000000
Incid. Location           0.178344
Comment                   0.000000
Equip.                    0.025478
Tot. Mins                 0.000000
Inc. Mins Delay Mins      0.000000
Delay Mins                0.000000
Capes                     0.000000
Pines                     0.000000
Calvs                     0.000000
FTS                       0.000000
Trains Affect             0.000000
EQ Mins                   0.000000
Mgrs Note                 0.000000
KPI                       0.000000
Bugle Status              0.000000
RSP Week                  0.000000
Inc. Pd                   0.000000
DfT Full                  0.000000
DfT Part                  0.000000
CaSL                      0.000000
PPM Fail                  0.000000
Incid. #                  0.000000
Div.s                     0.000000
Company                   0.000000
Full Canx                 0.000000
Part Canx                 0.000000
Total Canx                0.000000
Sig. Lates                0.000000
Total Mins                0.000000
W/E                       0.000000
Rep. Period               0.000000
KPI Cat.                  0.000000
CaSL's                    0.000000
PPM Fails                 0.000000
Sect1                     0.000000
Region.                   0.000000
Sect2                     0.000000
Day 8                     0.000000
NR KPI                    0.000000
TOC1                      0.000000
TOC2                      0.000000
Region                    0.000000
Funct.                    0.000000
Unnamed: 53             100.000000
1246.5                  100.000000
dtype: float64

In [15]:
Fleet_planning = pd.read_excel("/content/Fleet Planning Log.xlsx")

In [16]:
Fleet_planning.shape

(52, 55)

In [17]:
Fleet_planning.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 55 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   FPPM Balance Score Card 2022 / 2023  12 non-null     object
 1   Unnamed: 1                           35 non-null     object
 2   Period 1                             36 non-null     object
 3   Unnamed: 3                           38 non-null     object
 4   Unnamed: 4                           38 non-null     object
 5   Unnamed: 5                           38 non-null     object
 6   Period 2                             40 non-null     object
 7   Unnamed: 7                           38 non-null     object
 8   Unnamed: 8                           38 non-null     object
 9   Unnamed: 9                           38 non-null     object
 10  Period 3                             38 non-null     object
 11  Unnamed: 11                          38 non-null     object
 12  Unnamed: 12                          38 non-null     object
 13  Unnamed: 13                          38 non-null     object
 14  Period 4                             38 non-null     object
 15  Unnamed: 15                          38 non-null     object
 16  Unnamed: 16                          38 non-null     object
 17  Unnamed: 17                          38 non-null     object
 18  Period 5                             38 non-null     object
 19  Unnamed: 19                          38 non-null     object
 20  Unnamed: 20                          38 non-null     object
 21  Unnamed: 21                          38 non-null     object
 22  Period 6                             38 non-null     object
 23  Unnamed: 23                          38 non-null     object
 24  Unnamed: 24                          38 non-null     object
 25  Unnamed: 25                          38 non-null     object
 26  Period 7                             38 non-null     object
 27  Unnamed: 27                          38 non-null     object
 28  Unnamed: 28                          38 non-null     object
 29  Unnamed: 29                          38 non-null     object
 30  Period 8                             38 non-null     object
 31  Unnamed: 31                          38 non-null     object
 32  Unnamed: 32                          38 non-null     object
 33  Unnamed: 33                          38 non-null     object
 34  Period 9                             38 non-null     object
 35  Unnamed: 35                          38 non-null     object
 36  Unnamed: 36                          38 non-null     object
 37  Unnamed: 37                          38 non-null     object
 38  Period 10                            38 non-null     object
 39  Unnamed: 39                          38 non-null     object
 40  Unnamed: 40                          38 non-null     object
 41  Unnamed: 41                          38 non-null     object
 42  Period 11                            38 non-null     object
 43  Unnamed: 43                          38 non-null     object
 44  Unnamed: 44                          38 non-null     object
 45  Unnamed: 45                          38 non-null     object
 46  Period 12                            38 non-null     object
 47  Unnamed: 47                          38 non-null     object
 48  Unnamed: 48                          38 non-null     object
 49  Unnamed: 49                          38 non-null     object
 50  Period 13                            38 non-null     object
 51  Unnamed: 51                          38 non-null     object
 52  Unnamed: 52                          38 non-null     object
 53  Unnamed: 53                          38 non-null     object
 54  Unnamed: 54                          1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(54)
memory usage: 22.5+ KB

In [18]:
Fleet_planning.head()

,FPPM Balance Score Card 2022 / 2023,Unnamed: 1,Period 1,Unnamed: 3,Unnamed: 4,Unnamed: 5,Period 2,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 45,Period 12,Unnamed: 47,Unnamed: 48,Unnamed: 49,Period 13,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54
0,NaN,NaN,Week 1,Week 2,Week 3,Week 4,Week 1,Week 2,Week 3,Week 4,...,Week 4,Week 1,Week 2,Week 3,Week 4,Week 1,Week 2,Week 3,Week 4,NaT
1,NaN,NaN,2022-04-01 00:00:00,2022-04-10 00:00:00,2022-04-17 00:00:00,2022-04-24 00:00:00,2022-05-01 00:00:00,2022-05-08 00:00:00,2022-05-15 00:00:00,2022-05-22 00:00:00,...,2023-01-29 00:00:00,2023-02-05 00:00:00,2023-02-12 00:00:00,2023-02-19 00:00:00,2023-02-26 00:00:00,2023-03-05 00:00:00,2023-03-12 00:00:00,2023-03-19 00:00:00,2023-03-26 00:00:00,2023-04-01
2,Fleet Availability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,800/1,Number of Units Required,90,70,70,70,70,70,70,70,...,70,70,70,70,70,70,70,70,60,NaT

Warning: Total number of columns (55) exceeds max_columns (20) limiting to first (20) columns.

In [19]:
Fleet_planning.isnull().sum()

FPPM Balance Score Card 2022 / 2023    40
Unnamed: 1                             17
Period 1                               16
Unnamed: 3                             14
Unnamed: 4                             14
Unnamed: 5                             14
Period 2                               12
Unnamed: 7                             14
Unnamed: 8                             14
Unnamed: 9                             14
Period 3                               14
Unnamed: 11                            14
Unnamed: 12                            14
Unnamed: 13                            14
Period 4                               14
Unnamed: 15                            14
Unnamed: 16                            14
Unnamed: 17                            14
Period 5                               14
Unnamed: 19                            14
Unnamed: 20                            14
Unnamed: 21                            14
Period 6                               14
Unnamed: 23                            14
Unnamed: 24                            14
Unnamed: 25                            14
Period 7                               14
Unnamed: 27                            14
Unnamed: 28                            14
Unnamed: 29                            14
Period 8                               14
Unnamed: 31                            14
Unnamed: 32                            14
Unnamed: 33                            14
Period 9                               14
Unnamed: 35                            14
Unnamed: 36                            14
Unnamed: 37                            14
Period 10                              14
Unnamed: 39                            14
Unnamed: 40                            14
Unnamed: 41                            14
Period 11                              14
Unnamed: 43                            14
Unnamed: 44                            14
Unnamed: 45                            14
Period 12                              14
Unnamed: 47                            14
Unnamed: 48                            14
Unnamed: 49                            14
Period 13                              14
Unnamed: 51                            14
Unnamed: 52                            14
Unnamed: 53                            14
Unnamed: 54                            51
dtype: int64

In [20]:
Fleet_planning.isna().sum()/len(Fleet_planning)*100

FPPM Balance Score Card 2022 / 2023    76.923077
Unnamed: 1                             32.692308
Period 1                               30.769231
Unnamed: 3                             26.923077
Unnamed: 4                             26.923077
Unnamed: 5                             26.923077
Period 2                               23.076923
Unnamed: 7                             26.923077
Unnamed: 8                             26.923077
Unnamed: 9                             26.923077
Period 3                               26.923077
Unnamed: 11                            26.923077
Unnamed: 12                            26.923077
Unnamed: 13                            26.923077
Period 4                               26.923077
Unnamed: 15                            26.923077
Unnamed: 16                            26.923077
Unnamed: 17                            26.923077
Period 5                               26.923077
Unnamed: 19                            26.923077
Unnamed: 20                            26.923077
Unnamed: 21                            26.923077
Period 6                               26.923077
Unnamed: 23                            26.923077
Unnamed: 24                            26.923077
Unnamed: 25                            26.923077
Period 7                               26.923077
Unnamed: 27                            26.923077
Unnamed: 28                            26.923077
Unnamed: 29                            26.923077
Period 8                               26.923077
Unnamed: 31                            26.923077
Unnamed: 32                            26.923077
Unnamed: 33                            26.923077
Period 9                               26.923077
Unnamed: 35                            26.923077
Unnamed: 36                            26.923077
Unnamed: 37                            26.923077
Period 10                              26.923077
Unnamed: 39                            26.923077
Unnamed: 40                            26.923077
Unnamed: 41                            26.923077
Period 11                              26.923077
Unnamed: 43                            26.923077
Unnamed: 44                            26.923077
Unnamed: 45                            26.923077
Period 12                              26.923077
Unnamed: 47                            26.923077
Unnamed: 48                            26.923077
Unnamed: 49                            26.923077
Period 13                              26.923077
Unnamed: 51                            26.923077
Unnamed: 52                            26.923077
Unnamed: 53                            26.923077
Unnamed: 54                            98.076923
dtype: float64